### ISSUE TITLE
user CAS breaks ownCloud API

### ISSUE THREAD

**Issue by Xqua** [felixrupp/user_cas#11]
The module breaks the API somehow

When performing an API call, example:
`curl --silent -u admin:password 'https://cloud.mydomain.net/ocs/v1.php/cloud/users?search=user'`

I cannot perform the call and get this message as an anwser instead:
```<html><head><title>CAS logout wanted!</title></head><body><h1>CAS logout wanted!</h1><p>You should already have been redirected to the CAS server. Click <a href="https://cas.jogl.tech/logout?url=http%3A%2F%2Fcloud.jogl.tech%2F">here</a> to continue.</p><hr><address>phpCAS 1.3.5+ using server <a href="https://cas.jogl.tech/">https://cas.jogl.tech/</a> (CAS 2.0)</a></address></body></html>```

**Comment by Xqua** [comment]
If I activate the Force Login Option -> I have zero anwser from the API, not even an error message anymore.

I have to add, CAS works just fine, and everything works perfectly, except the API.

**Comment by Xqua** [comment]
And I fixed the error by Checking:
Disable CAS logout (do only OwnCloud logout)

**Comment by felixrupp** [comment]
Hi @Xqua,

thanks for your report! As I am not using the API myself, I never encountered the problem! I will try to disable user_cas on API calls only, as the main purpose of CAS is authenticating users via web browser only.

Regards

Felix

**Comment by felixrupp** [comment]
Hi @Xqua 

I hopefully fixed the check for the enforced authentication, so that ocs (onwCloud Service/API) calls are not broken any longer.

Can you please apply the following patch to your installation (please backup before) and give some feedback if your OC API is working correctly again with enforced authentication enabled? 

[user_cas-api-break-patch.diff](https://gist.github.com/felixrupp/bde3a479e4d904ed7d14cd54fec80e63)

If this will be positive, I'll be releasing the hotfixed version soon after.

Thank you!

Felix

**Comment by Xqua** [comment]
I'll try that ASAP thanks !
