### ISSUE TITLE
Problem During Single Sign Out

### ISSUE THREAD

**Issue by cheesgno** [felixrupp/user_cas#43]
Hi
I'm using you application on my nextcloud installation on docker (Version 14.0.3 with apache).
The login process works perfectly but I have some problems during the logout.
If I try to logout directly from nextcloud everythings works and the cas server send the logout messagge to all other services.
(for clarification nextcolud log report: phpCAS user is not authenticated, redirect to CAS server)
If I try to logout from any of the other application connected to my cas server, I receive on my nextcloud server the message from cas with the logout callback (somethind like: \/apps\/user_cas\/login?callback=jQuery33108167859672141691_1543102397821&logoutRequest=eJx9kF9LwzAUxb%2FKyHtr%2F6E1tGVClUVrhbXK9EWymJZIk9TclHXf3mxDmD74dOFczjk%2FTgZUDiOudK8nu%2BZfEwe7mOWgAB8%2FOZqMwpqCAKyo5IAtw83NY4UjP8Cj0VYzPaAFKXNUrb3Eq%2Fm4SnbdXb0bgG04WTF9Kbt0jxYv3IDQKkfO6QwAEycKLFXWSUGYemHoRUkbxTiOcXj1horsgIBrV0vKM6j%2FmSgAN9YVoWJZP7Xvz81tucwuzqJOuSNuOByAiPrgc9G0Dh6I1q%2BDV9337f4zZakszWaOg%2Bn6gTAKfs%2BlpL51EwnV%2B1uhheq0odIKBr6wW58p4%2B6p7E%2F%2Bj%2Fhr6eIbWrCEFg%3D%3D&_=1543102397822)  but the user session still up and running.
(for clarification nextcolud log report:  phpCAS user is already authenticated against owncloud)
Is it a bad configuration of my nextcloud instance?
Can ypu help me?
Thanks!!

**Comment by felixrupp** [comment]
Hi @cheesgno 

that seems to be a configuration problem. Did you properly setup the logout-servers in your CAS instance and the user_cas app? If your CAS session is already terminated, user_cas can not let you stay logged in because the CAS ticket is always being verified against your CAS server.

The ownCloud/Nextcloud session is another thing, so basically: you logout on your CAS, go back to your browser tab with Nextcloud and stay logged in there until you click on a link which needs authentication. Then you will be logged out/need to log in again. If you just stay on that view and don’t click anything, nothing will happen and it seems, that you’re still logged in.
