### ISSUE TITLE
What's the CAS login url?

### ISSUE THREAD

**Issue by fishfree** [felixrupp/user_cas#45]
After enabling this app, there is no CAS login link on the default Nextcloud login page. Only by checking the "Force user login using CAS", then will be redirected to the CAS sso login page. But when the CAS server redirects user to the Nextcloud page, Chrome said: too many redirects.

**Comment by felixrupp** [comment]
It appears to me, that your instance is not correctly configured. Please provide more details on which setup you are using with filling out the bug report form:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Software (please complete the following information):**
 - Server-OS: [e.g. Debian 9]
 - HTTP-Server Version: [e.g. Apache 2.2.0]
 - PHP-Version: [e.g. PHP 7.0]
 - phpCAS-Library-Version: [e.g. phpCAS  1.3.5]
 - ownCloud/Nextcloud Version [e.g. ownCloud 10.0.7/Nextcloud 13.0.0]
- user_cas-Version: [e.g. user_cas 1.5.0]


**Additional context**
Add any other context about the problem here.
