### ISSUE TITLE
403 Forbidden Access 

### ISSUE THREAD

**Issue by pllvpipalwa** [felixrupp/user_cas#92]
I am trying to implement the user_cas app with nextcloud.. I reckon that i am being successfully authenticated to the cas server but on redirection to nextcloud I see the below message:-
![image](https://user-images.githubusercontent.com/55120792/86895213-c7e55b00-c121-11ea-9daf-a25cef53ae5a.png)
I have already thoroughly referred to issue #52 
I was using user_ldap before implementing user_cas and I disabled it and also deleted everything from the database but I get the same error
I also tried a fresh installation without user_ldap and still can't make it work.
I am using Nexcloud 19.0.0 , phpcas 1.3.8, Ubuntu 18.0.4  and here are my phpcas logs
[log.txt](https://github.com/felixrupp/user_cas/files/4889433/log.txt)

**Comment by felixrupp** [comment]
Hi @pllvpipalwa 

the 403 error only appears, when you have successfully logged in your cas-server but the Nextcloud authentication fails or if you set up the authorization feature by groups and your user is not in a valid group.

To find out what the problem is, I need the Nextcloud log lines for one failed login attempt (without sensitive data of course). Then we can check what really happens.


Regards,
Felix
